### ISSUE TITLE
[Fix] Memory 이슈 해결

### ISSUE THREAD

**Issue by iDrogba** [TwoInterval/MacC-GoldenRatio#186]
## 구현해야하는 요소들
- 이미지 스티커를 수십 개 추가할 시 메모리 초과로 인한 App Terminate 오류 해결

<br>

## TODO
- [ ] 디버깅하기

<br>

## 비고 및 한계
- 아직 원인을 찾지 못해 Issue에 기록하지 못했습니다.

**Comment by iDrogba** [comment]
### 의심 시나리오 1
이미지를 업로드할 때 서버DB에 약 10:1 비율로 압축된 이미지를 업로드함.
-> 현재 로직상에선 압축되지 않은 이미지가 디스크 캐시에 저장이 됨.
-> 해당 이미지를 다시 사용할 때 디스크 캐시에 존재한다면 서버에서 다운로드하는 대신 디스크 캐시에 있는 이미지를 사용함.
-> 그러므로 내가 올린 모든 이미지는 원본이미지 상태로 다루어지게 됨.
-> 문제는 현재 캐시 로직인데. 디스크 캐시에 존재하는 이미지가 사용될 땐 다시 사용될 가능성이 높으므로 사용되는 순간에 메모리 캐시에도 올리도록 구현되어 있음.
-> 즉 모든 원본 크기 이미지가 메모리에 올라감.

**Comment by iDrogba** [comment]
<img width="1284" alt="스크린샷 2022-12-08 오후 12 39 21" src="https://user-images.githubusercontent.com/74828662/206352038-b25938f6-1649-48a8-a6ab-abf4b475de10.png">

**의심 시나리오 1** 과는 별개로 일차별 다이어리 화면에서 Bool 배열의 메모리 누수가 발견됨.

**Comment by Dorodong96** [comment]
다이어리 일차 뷰(`DiaryDaysViewController`)가 정상적으로 해제 되었음에도 불구하고, 계속해서 메모리에 남아있는 부분들이 있어서 해당 VC에 프로퍼티로 선언된 클래스 인스턴스들을 살펴보았습니다.
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/45297745/206601046-3136bdc2-748a-4d9a-bcd0-3505b23288f1.png">
위의 이미지에서 선언된 4개의 클래스에 대해 모두 `deinit`이 호출되면 print가 되도록 했으나, `albumCollectionView`와 `mapView`의 deinit이 제대로 이루어지지 않는 것을 확인하였습니다. (우선 해제 여부 테스트를 위해 optional로 선언해보았습니다.)
`albumCollectionView`와 `mapView` 프로퍼티 자체는 `DiaryDaysViewController`의 `deinit`과정에서 reference count가 감소하지만, 해당 클래스들의 인스턴스는 계속해서 메모리에 남아있는 것이 아닌가 의심이 됩니다.
문제 원인을 찾아보겠습니다!
